CREATE TABLE USERS (
	USERNAME VARCHAR(40) PRIMARY KEY,
	PASSWORD VARCHAR(40) NOT NULL,
	NAME VARCHAR(60) NOT NULL,
	EMAIL VARCHAR(60) NOT NULL,
	ROLE VARCHAR(40) NOT NULL
);

CREATE TABLE ADMIN_REQUESTS (
	USERNAME VARCHAR(40) PRIMARY KEY,
	NAME VARCHAR(60) NOT NULL
);

INSERT INTO USERS VALUES (
	'root',
	'rootpass',
	'root',
	'root@doubtsapp.com',
	'root'
);