CREATE TABLE USERS (
	USERNAME VARCHAR(40) PRIMARY KEY,
	PASSWORD VARCHAR(40) NOT NULL,
	NAME VARCHAR(60) NOT NULL,
	EMAIL VARCHAR(60) NOT NULL,
	ROLE VARCHAR(40) DEFAULT 'student'
);

CREATE TABLE ADMIN_REQUESTS (
	USERNAME VARCHAR(40) PRIMARY KEY,
	NAME VARCHAR(60) NOT NULL
);

CREATE TABLE COURSES (
	COURSECODE VARCHAR(10) PRIMARY KEY,
	COURSENAME VARCHAR(60) NOT NULL,
	INSTRUCTOR VARCHAR(40) NOT NULL,
	INSTRUCTORNAME VARCHAR(60) NOT NULL,
	FOREIGN KEY (INSTRUCTOR) REFERENCES USERS(USERNAME)
);

CREATE TABLE ENROLLMENT (
	COURSECODE VARCHAR(10),
	USERNAME VARCHAR(40),
	ROLE VARCHAR(20) NOT NULL,
	PRIMARY KEY (COURSECODE,USERNAME),
	FOREIGN KEY (COURSECODE) REFERENCES COURSES (COURSECODE),
	FOREIGN KEY (USERNAME) REFERENCES USERS (USERNAME)
);

CREATE TABLE ENROLLMENT_REQUESTS (
	COURSECODE VARCHAR(10),
	USERNAME VARCHAR(40),
	RELATION VARCHAR(20),
	PRIMARY KEY (COURSECODE, USERNAME),
	FOREIGN KEY (COURSECODE) REFERENCES COURSES (COURSECODE),
	FOREIGN KEY (USERNAME) REFERENCES USERS (USERNAME)
);

INSERT INTO USERS VALUES (
	'root',
	'root',
	'root',
	'root',
	'root'
);